### ISSUE TITLE
non recursive module listing requires currently nonexisting -d (--dirs) option

### ISSUE THREAD

**Issue by perlundq** [perlundq/yajsync#1]
```
# already running yajsyncd on port 14415
$ rsync rsync://localhost:14415
Downloads      
Uploads        
Downloads2     
$ rsync rsync://localhost:14415/Downloads
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [Receiver=3.0.9]

# yajsyncd error log:
Jan 10, 2014 7:42:35 PM com.github.perlundq.yajsync.ui.YajSyncServer$8 call
SEVERE: 
com.github.perlundq.yajsync.session.RsyncProtocolException: com.github.perlundq.yajsync.util.ArgumentParsingError: d - unknown option
        at com.github.perlundq.yajsync.session.ServerSessionConfig.handshake(ServerSessionConfig.java:123)
        at com.github.perlundq.yajsync.session.RsyncServerSession.startSession(RsyncServerSession.java:155)
        at com.github.perlundq.yajsync.ui.YajSyncServer$8.call(YajSyncServer.java:198)
        at com.github.perlundq.yajsync.ui.YajSyncServer$8.call(YajSyncServer.java:190)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
Caused by: com.github.perlundq.yajsync.util.ArgumentParsingError: d - unknown option
        at com.github.perlundq.yajsync.util.ArgumentParser.getOptionForName(ArgumentParser.java:309)
        at com.github.perlundq.yajsync.util.ArgumentParser.parse(ArgumentParser.java:129)
        at com.github.perlundq.yajsync.session.ServerSessionConfig.parseArguments(ServerSessionConfig.java:261)
        at com.github.perlundq.yajsync.session.ServerSessionConfig.handshake(ServerSessionConfig.java:118)
        ... 8 more

```
see options.c:server_options() and options.c:parse_arguments()

xfer_dirs is initialized to -1 and if doing non-recursive module listing it is set to 1...

**Comment by perlundq** [comment]
support for --dirs has been added in dc0ef6f6624de7e640f19e9e37605cb02171358f
