### ISSUE TITLE
Exception propagation for SystemTests

### ISSUE THREAD

**Issue by usrflo** [perlundq/yajsync#42]
Writing a system test for timeout detection I'm ending up with the logging output of the stacktrace below (which is correct and expected). In this test I'm using the YajSyncClient that does not propagate exceptions but returns the result code like the native rsync client is doing. What options do you see to enable exception propagation if YajSyncClient/Server should be testable with annotations like 

> @Test(expected=SocketTimeoutException.class)

 ?

```
com.github.perlundq.yajsync.channels.ChannelException: java.net.SocketTimeoutException
	at com.github.perlundq.yajsync.channels.SimpleInputChannel.get(SimpleInputChannel.java:134)
	at com.github.perlundq.yajsync.channels.SimpleInputChannel.getByte(SimpleInputChannel.java:62)
	at com.github.perlundq.yajsync.channels.BufferedDuplexChannel.getByte(BufferedDuplexChannel.java:92)
	at com.github.perlundq.yajsync.channels.AutoFlushableDuplexChannel.getByte(AutoFlushableDuplexChannel.java:41)
	at com.github.perlundq.yajsync.session.SessionConfig.readLine(SessionConfig.java:112)
	at com.github.perlundq.yajsync.session.SessionConfig.receivePeerVersion(SessionConfig.java:167)
	at com.github.perlundq.yajsync.session.SessionConfig.exchangeProtocolVersion(SessionConfig.java:93)
	at com.github.perlundq.yajsync.session.ClientSessionConfig.handshake(ClientSessionConfig.java:83)
	at com.github.perlundq.yajsync.RsyncClient$ModuleListing$1.call(RsyncClient.java:247)
	at com.github.perlundq.yajsync.RsyncClient$ModuleListing$1.call(RsyncClient.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:229)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at com.github.perlundq.yajsync.channels.net.StandardSocketChannel.read(StandardSocketChannel.java:83)
	at com.github.perlundq.yajsync.channels.SimpleInputChannel.get(SimpleInputChannel.java:122)
	... 13 more
```

**Comment by perlundq** [comment]
Yeah, my plan was to use RsyncClient and RsyncServer for most of these kind of integration tests.
