### ISSUE TITLE
test failure in testConnectionTimeout

### ISSUE THREAD

**Issue by grexe** [perlundq/yajsync#48]
cloning latest master as of today and running the tests gives me the following error on Linux x86-64 (Ubuntu 16.04) kernel 4.5.1-040501-generic, Oracle JDK 8 (build 1.8.0_91-b14, 64bit server), Apache Maven 3.3.9:
```
testConnectionTimeout(com.github.perlundq.yajsync.test.SystemTest): Unexpected exception, expected<java.net.SocketTimeoutException> but was<java.net.SocketException>

Running com.github.perlundq.yajsync.test.SystemTest
drwxrwxr-x           2 2016/06/24 17:27:34 ./
test           	a test module
Jun 24, 2016 5:27:35 PM com.github.perlundq.yajsync.internal.session.ServerSessionConfig handshake
WARNING: failed to authenticate 
drwxrwxr-x           2 2016/06/24 17:27:35 ./
drwxrwxr-x           3 2016/06/24 17:27:35 ./
-rw-rw-r--           0 2016/06/24 17:27:35 ./file
Tests run: 32, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.672 sec <<< FAILURE!
testConnectionTimeout(com.github.perlundq.yajsync.test.SystemTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.net.SocketTimeoutException> but was<java.net.SocketException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:274)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:268)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:102)
	at com.github.perlundq.yajsync.net.StandardSocketChannel.open(StandardSocketChannel.java:53)
	at com.github.perlundq.yajsync.net.StandardChannelFactory.open(StandardChannelFactory.java:27)
	at com.github.perlundq.yajsync.test.SystemTest.testConnectionTimeout(SystemTest.java:1000)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 4 more
```

**Comment by perlundq** [comment]
mmm, yes that test is fragile and depends on the host's network configuration and should probably be disabled.
Thank you for the report.

**Comment by usrflo** [comment]
I checked for alternatives to test the connection timeout: connecting to a non-routable IP is a workaround that may fail depending on the host's network and I didn't find a suitable replacement.

I agree to disable this test.
